/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssociationRouteImport } from './routes/association'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as EducationRouteImport } from './routes/education'
import { Route as EventsRouteImport } from './routes/events'
import { Route as Prohair2026RouteImport } from './routes/prohair-2026'
import { Route as Prohair2027RouteImport } from './routes/prohair-2027'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationRoute = AssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const Prohair2026Route = Prohair2026RouteImport.update({
  id: '/prohair-2026',
  path: '/prohair-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const Prohair2027Route = Prohair2027RouteImport.update({
  id: '/prohair-2027',
  path: '/prohair-2027',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/association': typeof AssociationRoute
  '/contacts': typeof ContactsRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/prohair-2026': typeof Prohair2026Route
  '/prohair-2027': typeof Prohair2027Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/association': typeof AssociationRoute
  '/contacts': typeof ContactsRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/prohair-2026': typeof Prohair2026Route
  '/prohair-2027': typeof Prohair2027Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/association': typeof AssociationRoute
  '/contacts': typeof ContactsRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/prohair-2026': typeof Prohair2026Route
  '/prohair-2027': typeof Prohair2027Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/association'
    | '/contacts'
    | '/education'
    | '/events'
    | '/prohair-2026'
    | '/prohair-2027'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/association'
    | '/contacts'
    | '/education'
    | '/events'
    | '/prohair-2026'
    | '/prohair-2027'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/association'
    | '/contacts'
    | '/education'
    | '/events'
    | '/prohair-2026'
    | '/prohair-2027'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssociationRoute: typeof AssociationRoute
  ContactsRoute: typeof ContactsRoute
  EducationRoute: typeof EducationRoute
  EventsRoute: typeof EventsRoute
  Prohair2026Route: typeof Prohair2026Route
  Prohair2027Route: typeof Prohair2027Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association': {
      id: '/association'
      path: '/association'
      fullPath: '/association'
      preLoaderRoute: typeof AssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohair-2026': {
      id: '/prohair-2026'
      path: '/prohair-2026'
      fullPath: '/prohair-2026'
      preLoaderRoute: typeof Prohair2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohair-2027': {
      id: '/prohair-2027'
      path: '/prohair-2027'
      fullPath: '/prohair-2027'
      preLoaderRoute: typeof Prohair2027RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssociationRoute: AssociationRoute,
  ContactsRoute: ContactsRoute,
  EducationRoute: EducationRoute,
  EventsRoute: EventsRoute,
  Prohair2026Route: Prohair2026Route,
  Prohair2027Route: Prohair2027Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
